ppbt_22_option_crud
NatMyronenko/java-test-junior-developer pull request #41
Opened 2023-04-06 11:17 UTC by aleksdenni

2023-04-07 05:00 UTC, alex97po requested changes

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/controller/OptionController.java
> +  public OptionDto getOption(@PathVariable @Valid Long id) {
What is the purpose of `@Valid` here?

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/controller/OptionController.java
> +  public OptionDto updateOption(@PathVariable @Valid Long id,
Same question - what `@Valid` near Long means?

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/dto/OptionDto.java
> +@RequiredArgsConstructor
What is the purpose of this annotation?

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/dto/OptionDto.java
> +  @NotNull Long id;
Client cannot send you id during option creation. So this will not work.

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/mapper/CategoryMapper.java
> +  @Autowired
No need in this annotation

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/mapper/CategoryMapper.java
> +  public CategoryMapper(LanguageService languageService) {
Use `@RequiredArgsConstructor` instead

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/mapper/CategoryMapper.java
> +        .language(languageService.getLanguage(dto.getId()))
This is not correct. Id in CategoryDto refers to CATEGORY id, and not language id. You should add languageId field to CategoryDto and use it to find language.

2023-04-07 05:00 UTC, alex97po commented on src/main/java/com/example/java/test/junior/developer/model/Category.java
> +@Getter
Why have you made these changes? What about equals/hashCode/toString? How it will work now without `@Data`?

2023-04-18 14:59 UTC, alex97po submitted a review, later dismissed

2023-04-18 16:33 UTC, NatMyronenko approved these changes

2023-04-18 16:34 UTC, merged